services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/amakantuabunauzor/nan-instagram-ai
    dockerContext: .
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
